"""Build an HTML email report from a list of profiled guest dicts."""

from datetime import date

STYLES = """
body { margin: 0; padding: 0; background: #f4f4f4; font-family: Arial, sans-serif; color: #333; }
.wrapper { max-width: 700px; margin: 0 auto; padding: 24px 16px; }
h1 { font-size: 22px; color: #1a1a2e; margin-bottom: 4px; }
.subtitle { font-size: 13px; color: #888; margin-bottom: 28px; }
.card { background: #ffffff; border-radius: 8px; padding: 20px 24px; margin-bottom: 20px;
        box-shadow: 0 1px 4px rgba(0,0,0,.08); }
.card-header { display: flex; align-items: flex-start; gap: 16px; margin-bottom: 12px; }
.photo { width: 72px; height: 72px; border-radius: 50%; object-fit: cover;
         border: 2px solid #e0e0e0; flex-shrink: 0; }
.photo-placeholder { width: 72px; height: 72px; border-radius: 50%;
                     background: #e8eaf6; display: flex; align-items: center;
                     justify-content: center; font-size: 28px; flex-shrink: 0; }
.name { font-size: 18px; font-weight: bold; color: #1a1a2e; margin: 0 0 4px; }
.meta { font-size: 13px; color: #666; margin: 0; line-height: 1.6; }
.summary { font-size: 14px; line-height: 1.65; margin-bottom: 12px; }
.links-label { font-size: 12px; font-weight: bold; text-transform: uppercase;
               letter-spacing: .05em; color: #888; margin-bottom: 4px; }
.links { list-style: none; padding: 0; margin: 0; }
.links li { margin-bottom: 4px; }
.links a { color: #3949ab; font-size: 13px; text-decoration: none; }
.links a:hover { text-decoration: underline; }
.empty { text-align: center; padding: 48px 0; color: #999; font-size: 15px; }
.footer { text-align: center; font-size: 11px; color: #bbb; margin-top: 32px; }
"""


def _fmt_date(iso: str) -> str:
    """Format 'YYYY-MM-DD' as 'Mon DD, YYYY'."""
    if not iso:
        return "—"
    try:
        return date.fromisoformat(iso).strftime("%b %d, %Y")
    except ValueError:
        return iso


def _guest_card(guest: dict) -> str:
    profile = guest.get("profile", {})
    full_name = f"{guest.get('first_name', '')} {guest.get('last_name', '')}".strip() or "Unknown Guest"
    photo_url = profile.get("photo_url")
    summary = profile.get("summary", "")
    links = profile.get("links", [])

    location_parts = [guest.get("city", ""), guest.get("state", ""), guest.get("country", "")]
    location = ", ".join(p for p in location_parts if p) or "—"

    check_in = _fmt_date(guest.get("check_in", ""))
    check_out = _fmt_date(guest.get("check_out", ""))
    villa = guest.get("villa", "—") or "—"
    language = guest.get("language", "—") or "—"

    if photo_url:
        photo_html = f'<img src="{photo_url}" alt="{full_name}" class="photo">'
    else:
        photo_html = '<div class="photo-placeholder">👤</div>'

    links_html = ""
    if links:
        items = "\n".join(f'<li><a href="{url}">{url}</a></li>' for url in links)
        links_html = f"""
        <div class="links-label">Links</div>
        <ul class="links">{items}</ul>
        """

    return f"""
    <div class="card">
      <div class="card-header">
        {photo_html}
        <div>
          <p class="name">{full_name}</p>
          <p class="meta">
            Check-in: {check_in} &nbsp;|&nbsp; Check-out: {check_out}<br>
            Villa: {villa} &nbsp;|&nbsp; Language: {language}<br>
            Location: {location}
          </p>
        </div>
      </div>
      <p class="summary">{summary}</p>
      {links_html}
    </div>
    """


def build_html(guests_with_profiles: list[dict]) -> str:
    """Render a full HTML email from a list of profiled guest dicts."""
    today = date.today().strftime("%B %d, %Y")

    if guests_with_profiles:
        cards = "\n".join(_guest_card(g) for g in guests_with_profiles)
        body_html = cards
    else:
        body_html = '<p class="empty">No guests arriving in the next 7 days.</p>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Anticipatory Guest Report</title>
  <style>{STYLES}</style>
</head>
<body>
  <div class="wrapper">
    <h1>Anticipatory Guest Report</h1>
    <p class="subtitle">Arrivals in the next 7 days &mdash; generated {today}</p>
    {body_html}
    <p class="footer">This report is auto-generated by Sabueso. Do not reply.</p>
  </div>
</body>
</html>"""
